//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.RentalOrders = new HashSet<RentalOrder>();
        }
    
        public int CarID { get; set; }
        public int CarTypeID { get; set; }
        public int BranchID { get; set; }
        public string CarPlateNumber { get; set; }
        public string CarType { get; set; }
        public int CurrentMileage { get; set; }
        public string Photo { get; set; }
        public bool Rentable { get; set; }
    
        public virtual CarsType CarsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalOrder> RentalOrders { get; set; }
    }
}
